### ISSUE TITLE
Error while bringing the application up after the upgrade to v1.14.0

### ISSUE THREAD

**Issue by kohli-rahul** [quarkiverse/quarkus-authzed-client#23]
Error while bringing the application up after the upgrade to v1.14.0, since the application is expecting the output from the container console and the text has now modified post upgrade.

**Comment by kohli-rahul** [comment]
@iocanel  - Could you provide access to this repo. I can help in fixing some of these issues.

**Comment by gsmet** [comment]
@kohli-rahul you don't need access to the repository, you can create pull requests for @iocanel to review.

**Comment by iocanel** [comment]
Fixed as part of #24
